basePath: /
definitions:
  handler.ShortenURLRequest:
    properties:
      url:
        example: https://example.com
        type: string
    type: object
  handler.ShortenURLResponse:
    properties:
      shortened:
        example: http://localhost:8080/abc123
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a simple URL shortener service.
  title: URL Shortener API
  version: "1.0"
paths:
  /{shortID}:
    get:
      description: Redirects the user to the original URL associated with the shortened
        ID
      parameters:
      - description: Shortened ID
        in: path
        name: shortID
        required: true
        type: string
      responses:
        "302":
          description: Redirects to the original URL
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Redirect to original URL
  /shorten:
    post:
      consumes:
      - application/json
      description: Shortens a given URL and returns a shortened version
      parameters:
      - description: URL to shorten
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.ShortenURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShortenURLResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Shorten a URL
swagger: "2.0"
